version: "3"

services:
  ark-ded:
    image: lyuhau/ark-ded:latest
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    network_mode: host
#    ports:
#      - 27015:27015/udp
#      - 7777:7777/udp
#      - 7778:7778/udp
#      - 27020:27020/tcp
    privileged: true
    volumes:
      - ./${INSTANCE}/config:/mnt/ark-ded/instance/config:ro
      - ./${INSTANCE}/${SAVE}:/mnt/ark-ded/instance/SavedArks
      - ./clusters/${CLUSTER}:/mnt/ark-ded/common/cluster
      - ./Config:/mnt/ark-ded/common/Config
      - ./modlist.ini:/mnt/ark-ded/mods/modlist.ini:ro
      - ./Mods:/mnt/ark-ded/mods/Mods
